# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git clone https://github.com/TWBug/GoldCardHenge.git
    git config --global user.name "TWBug"
    git checkout main
    git add .
    git commit -m "autoSync"
    git push https://dev.azure.com/TWBug/goldcardBK/_git/GoldCardHenge
  displayName: 'Run a sync script'
