# backend:
#     name: git-gateway
#     branch: master # Branch to update (optional; defaults to master)

# Auth directly with github
# SEE https://www.netlifycms.org/docs/backends-overview/
# NOTE I'm not sure exactly what site_domain is required for. It works fine on
# localhost without this, but not on staging.taiwangoldcard.tw.
backend:
    name: github
    repo: tego-tech/www
    site_domain: staging.taiwangoldcard.tw # See NOTE

site_url: https://staging.taiwangoldcard.tw

# The language of the admin UI
# Set to 'zh_Hant' for 繁體中文
locale: 'en'

# Whether or not ot interact directly with the local git repo rather than the
# remote repo on github. Requires `npx netlify-cms-proxy-server` running.
# These settings only apply on localhost.
local_backend: true

# Customize the logo that displays on the sign-in page (just found this logo via web search)
logo_url: 'https://images.squarespace-cdn.com/content/v1/54fda45ae4b056e88666306d/1522048397733-V0ID9KLHK9KPYBQQQMV1/ke17ZwdGBToddI8pDm48kLu6I4ew71KXDwr0TupZA2UUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKc_EzImbYIQh6Bf_ScjyA5THHFXQ368Ng-_1uc2knSgWnGpDWSCaGBnv7W-TNEDThe/taiwan-national-development-council.jpg'

i18n:
    # Required and can be one of multiple_folders, multiple_files or single_file
    # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
    # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
    # single_file - persists a single file in `<folder>/<slug>.<extension>`
    structure: multiple_files

    # Required - a list of locales to show in the editor UI
    locales: [en, zh]

    # Optional, defaults to the first item in locales.
    # The locale to be used for fields validation and as a baseline for the entry.
    default_locale: en

# Require posts to be "ready" before finally publishing them
publish_mode: editorial_workflow

# Media files will be stored in the repo under here
media_folder: 'assets/cms-uploads'

# The src attribute for uploaded media will begin with this
public_folder: '/cms-uploads'

# The various collections we use for the site. They correspond to directories of content
collections:
    # Top-level pages. NOTE: The home page is configured separately because it is so customized.
    - name: 'pages'
      label: 'Pages'
      description: >
          Top-level pages for the site.
      folder: 'content'
      create: true
      slug: '{{slug}}'
      i18n: true
      preview_path: en/{{slug}}
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: duplicate }
          - { label: 'Draft?', name: 'draft', widget: 'boolean', default: true, i18n: duplicate }
          - { label: 'Hidden?', name: 'hidden', widget: 'boolean', default: false, i18n: true }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    # Home page
    - name: 'home_page'
      label: 'Home Page'
      description: >
          Content on the Home page. The items listed here are sections of the home page rather than individual pages.

          NOTE: The unique nature of the Home page means we need to configure the language separately for now. There is an open issue to address this: https://github.com/netlify/netlify-cms/issues/4483
      slug: '{{slug}}'
      preview_path: en/
      files:
          - label: 'Hero (en)'
            name: 'hero_en'
            file: 'content/home/hero.en.md'
            fields:
                - { label: 'Title', name: 'title', widget: 'string', i18n: true }
                - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
                - { label: 'Draft?', name: 'draft', widget: 'boolean', default: false, i18n: duplicate }
                - { label: 'Hidden?', name: 'hidden', widget: 'hidden', default: false, i18n: duplicate }
                - { label: 'Headless?', name: 'headless', widget: 'hidden', default: true, i18n: duplicate }
                - label: 'Links'
                  name: 'links'
                  widget: 'list'
                  fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Link, name: href, description: 'Link to where?', widget: string }
                      - { label: CTA?, name: is_cta, widget: boolean, default: false }
                - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
          - label: 'Hero (zh)'
            name: 'hero_zh'
            file: 'content/home/hero.zh.md'
            fields:
                - { label: 'Title', name: 'title', widget: 'string', i18n: true }
                - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
                - { label: 'Draft?', name: 'draft', widget: 'boolean', default: false, i18n: duplicate }
                - { label: 'Hidden?', name: 'hidden', widget: 'hidden', default: false, i18n: duplicate }
                - { label: 'Headless?', name: 'headless', widget: 'hidden', default: true, i18n: duplicate }
                - label: 'Links'
                  name: 'links'
                  widget: 'list'
                  fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Link, name: href, description: 'Link to where?', widget: string }
                      - { label: CTA?, name: is_cta, widget: boolean, default: false }
                - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
          - label: 'Intro (en)'
            name: 'intro_en'
            file: 'content/home/intro.en.md'
            fields:
                - { label: 'Title', name: 'title', widget: 'string', i18n: true }
                - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
                - { label: 'Draft?', name: 'draft', widget: 'boolean', default: false, i18n: duplicate }
                - { label: 'Hidden?', name: 'hidden', widget: 'hidden', default: false, i18n: duplicate }
                - { label: 'Headless?', name: 'headless', widget: 'hidden', default: true, i18n: duplicate }
                - label: 'Links'
                  name: 'links'
                  widget: 'list'
                  fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Link, name: href, description: 'Link to where?', widget: string }
                      - { label: CTA?, name: is_cta, widget: boolean, default: false }
                - label: 'Sub-page Links'
                  name: 'sub_page_links'
                  widget: 'list'
                  fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Link, name: href, description: 'Link to where?', widget: string }
                      - { label: CTA?, name: is_cta, widget: boolean, default: false }
                - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
          - label: 'Intro (zh)'
            name: 'intro_zh'
            file: 'content/home/intro.zh.md'
            fields:
                - { label: 'Title', name: 'title', widget: 'string', i18n: true }
                - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
                - { label: 'Draft?', name: 'draft', widget: 'boolean', default: false, i18n: duplicate }
                - { label: 'Hidden?', name: 'hidden', widget: 'hidden', default: false, i18n: duplicate }
                - { label: 'Headless?', name: 'headless', widget: 'hidden', default: true, i18n: duplicate }
                - label: 'Links'
                  name: 'links'
                  widget: 'list'
                  fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Link, name: href, description: 'Link to where?', widget: string }
                      - { label: CTA?, name: is_cta, widget: boolean, default: false }
                - label: 'Sub-page Links'
                  name: 'sub_page_links'
                  widget: 'list'
                  fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Link, name: href, description: 'Link to where?', widget: string }
                      - { label: CTA?, name: is_cta, widget: boolean, default: false }
                - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'legal'
      label: 'Legal'
      folder: 'content/legal'
      create: true
      slug: '{{slug}}'
      i18n: true
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: duplicate }
          - { label: 'Draft?', name: 'draft', widget: 'boolean', default: false, i18n: duplicate }
          - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false, i18n: duplicate }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'events'
      label: 'Events'
      folder: 'content/events'
      create: true
      slug: '{{slug}}'
      i18n: true
      fields:
          - { label: 'Event Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Event Date', name: 'date', widget: 'datetime', i18n: duplicate }
          - { label: 'Accupass Link', name: 'link', widget: 'string', i18n: duplicate }
          # - { label: 'Draft?', name: 'draft', widget: 'boolean', default: false, i18n: duplicate }
          # - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false, i18n: duplicate }
          # - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'jobs'
      label: 'Jobs'
      folder: 'content/jobs'
      create: true
      slug: '{{slug}}'
      preview_path: en/jobs/{{slug}}
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Draft?', name: 'draft', widget: 'hidden', default: false, i18n: duplicate }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'faq'
      label: 'FAQ'
      folder: 'content/faq'
      create: true
      slug: '{{slug}}'
      preview_path: en/faq/{{slug}}
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Draft?', name: 'draft', widget: 'hidden', default: false, i18n: duplicate }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'why-taiwan'
      label: 'Why Taiwan'
      folder: 'content/why-taiwan'
      create: true
      slug: '{{slug}}'
      preview_path: en/why-taiwan/{{slug}}
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Draft?', name: 'draft', widget: 'hidden', default: false, i18n: duplicate }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'qualification'
      label: 'Qualification'
      folder: 'content/qualification'
      create: true
      slug: '{{slug}}'
      preview_path: en/qualification/{{slug}}
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Draft?', name: 'draft', widget: 'hidden', default: false, i18n: duplicate }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'news' # Used in routes, e.g., /admin/collections/news
      label: 'News' # Used in the UI
      folder: 'content/news' # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., my-title.md
      preview_path: en/news/{{slug}}

      # Same as the top level i18n config, but all fields are optional and
      # defaults to the top level can also be a boolean to accept the top level
      # defaults
      i18n: true

      # SEE https://www.netlifycms.org/docs/widgets#boolean
      # For notes on the i18n support:
      # SEE # https://www.netlifycms.org/docs/beta-features/#i18n-support
      # The field-level i18n config shoudl be true|duplicate or omitted.
      # Omitting it will cause the field not to be copied over., so that's
      # probably not wnat is desired.
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: duplicate }
          - { label: 'Draft?', name: 'draft', widget: 'boolean', default: true, i18n: duplicate }
          - label: 'Tags'
            name: 'tags'
            widget: 'relation'
            collection: 'taxonomies'
            file: 'tag_data'
            value_field: 'items.*'
            search_fields: ['items.*']
            multiple: true
            required: false
            i18n: duplicate
          - label: 'Category'
            name: 'category'
            widget: 'relation'
            collection: 'taxonomies'
            file: 'category_data'
            value_field: 'items.*'
            search_fields: ['items.*']
            multiple: false # Only allow one category
            required: false
            i18n: duplicate
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'taxonomies'
      label: 'Taxonomies'
      editor:
          preview: false
      description: >
          All the tags and categories used throughtout the site.
      files:
          - label: 'Tags'
            name: 'tag_data'
            file: 'data/tags.yaml'
            fields:
                - label: 'Tags'
                  name: 'items'
                  widget: 'list'
                  summary: '{{fields.name}}'
                  field: { label: Tag Name, name: name, widget: string }
          - label: 'Categories'
            name: 'category_data'
            file: 'data/categories.yaml'
            fields:
                - label: 'Categories'
                  name: 'items'
                  widget: 'list'
                  summary: '{{fields.name}}'
                  field: { label: Tag Name, name: name, widget: string }

    # Configure the site. Menus for example
    - name: 'config'
      label: 'Config'
      description: >
          Configuration for the site. This is where you will find things like
          menus and their ordering in the UI.

          NOTE: We cannot currently configure English and 中文 at the same time. There is an open issue to address this: https://github.com/netlify/netlify-cms/issues/4483
      editor:
          preview: false
      files:
          - label: 'Navigation (en)'
            name: 'navigation_en'
            file: 'data/en/navigation.yaml'
            fields:
                - label: 'Navigation Items'
                  name: 'items'
                  widget: 'list'
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Link, name: folder, widget: string }
                      - { label: Link, name: link, widget: string }
          - label: 'Navigation (zh)'
            name: 'navigation_zh'
            file: 'data/zh/navigation.yaml'
            fields:
                - label: 'Navigation Items'
                  name: 'items'
                  widget: 'list'
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Link, name: folder, widget: string }
                      - { label: Link, name: link, widget: string }
