# backend:
#     name: git-gateway
#     branch: master # Branch to update (optional; defaults to master)

# Auth directly with github
# SEE https://www.netlifycms.org/docs/backends-overview/
# NOTE I'm not sure exactly what site_domain is required for. It works fine on
# localhost without this, but not on staging.taiwangoldcard.tw.
backend:
    name: github
    repo: tego-tech/www
    site_domain: www.taiwangoldcard.tw # See NOTE

publish_mode: editorial_workflow
media_folder: 'static/img/uploads' # Media files will be stored in the repo under static/img/uploads
public_folder: '/img/uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
    - name: 'blog' # Used in routes, e.g., /admin/collections/blog
      label: 'Blog' # Used in the UI
      folder: 'content/blog' # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., my-title.md

      # SEE https://www.netlifycms.org/docs/widgets#boolean
      fields: # The fields for each document, usually in front matter
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Draft?', name: 'draft', widget: 'boolean', default: true }
          - { label: 'Body', name: 'body', widget: 'markdown' }
