name: Deploy Github Pages

on:
    push:
        branches:
            - prod

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.74.3'

            - name: Build Hugo
              run: hugo --minify --environment gh

            - name: Deploy Hugo
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: './public'
                  cname: gh.taiwangoldcard.tw
